package domain

import models.DeliveryMethod.DeliveryMethod
import models.PaymentMethod.PaymentMethod

sealed trait OrderingProcessFSMCommand

case object CreateOrderCommand extends OrderingProcessFSMCommand

case class AddItemToShoppingCartCommand(product: models.Product) extends OrderingProcessFSMCommand

case object CheckoutCommand extends OrderingProcessFSMCommand

case class ChooseDeliveryMethodCommand(deliveryMethod: DeliveryMethod) extends OrderingProcessFSMCommand

case class ChoosePaymentMethodCommand(paymentMethod: PaymentMethod) extends OrderingProcessFSMCommand

case object ProcessOrderCommand extends OrderingProcessFSMCommand
